QUERIES = {
    'truncate_temp': """DELETE FROM optiwaretemp.SRC_PRD_AFITECH_DAILYPAYMENT""",
    'insert_temp': """INSERT INTO optiwaretemp.SRC_PRD_AFITECH_DAILYPAYMENT("JOUR"
,"PARTNER" ,"PAYMENT_PROVIDER" ,"TOTAL_AMOUNT_OF_DEPOSIT" ,"TOTAL_NUMBER_OF_DEPOSIT"
,"TOTAL_AMOUNT_OF_WITHDRAWALS" ,"TOTAL_NUMBER_OF_WITHDRAWALS" ,"TOTAL_COMMISSIONS")
VALUES(:1,:2,:3,:4,:5,:6,:7,:8)""", # Manque T_AMOUNT_OF_PARTNER_DEPOSITS, T_AM_OF_PARTNER_WITHDRAWALS par rapport au script original mais ils ne sont pas utilisés dans la suite
    'delete_main_dtm_table': """DELETE FROM user_dwhpr.DTM_MISE_AFITECH_DAILYPAYMENT
WHERE idtemps IN (SELECT idtemps FROM user_dwhpr.dim_temps WHERE jour BETWEEN :date_debut AND :date_fin )""",
    'insert_main_dtm_table': """INSERT INTO user_dwhpr.DTM_MISE_AFITECH_DAILYPAYMENT(
JOUR ,PARTNER ,PAYMENT_PROVIDER ,TOTAL_AMOUNT_OF_DEPOSIT ,TOTAL_NUMBER_OF_DEPOSIT
,TOTAL_AMOUNT_OF_WITHDRAWALS ,TOTAL_NUMBER_OF_WITHDRAWALS ,TOTAL_COMMISSIONS ,IDTEMPS,MOIS, ANNEE )
(
    SELECT TO_CHAR(TO_DATE(TRIM(SUBSTR(f.jour,1,10)),'YYYY/MM/DD'),'DD/MM/YYYY') JOUR
        ,PARTNER ,PAYMENT_PROVIDER ,NVL(TOTAL_AMOUNT_OF_DEPOSIT,0) ,NVL(TOTAL_NUMBER_OF_DEPOSIT,0)
        ,NVL(TOTAL_AMOUNT_OF_WITHDRAWALS,0) ,NVL(TOTAL_NUMBER_OF_WITHDRAWALS,0) ,NVL(TOTAL_COMMISSIONS,0)
        ,Te.idtemps AS IDTEMPS,Te.MOISC AS MOIS,Te.ANNEEC AS ANNEE
        FROM optiwaretemp.SRC_PRD_AFITECH_DAILYPAYMENT F, user_dwhpr.DIM_TEMPS Te
        WHERE TO_DATE(TRIM(SUBSTR(f.jour,1,10)),'YYYY/MM/DD') = TO_DATE(TRIM(SUBSTR(Te.jour,1,10)),'DD/MM/RR')
)""",
    'cleanup_temp': """DELETE FROM optiwaretemp.SRC_PRD_AFITECH_DAILYPAYMENT"""
}

def get_queries():
    return QUERIES
