QUERIES = {
    'truncate_temp': """DELETE FROM optiwaretemp.SRC_PRD_AFITECH_COMMISSION""",
    'insert_temp': """INSERT INTO optiwaretemp.SRC_PRD_AFITECH_COMMISSION("DEBUT_PERIODE"
,"FIN_PERIODE" ,"PARTNER" ,"PAYEMENT_PROVIDER" ,"TOTAL_COMMISSON" ,"DEPOSIT_TOTAL_AMOUNT"
,"DEPOSIT_COUNT" ,"WITHDRAWAL_TOTAL_AMOUNT" ,"WITHDRAWAL_COUNT")
VALUES(:1,:2,:3,:4,:5,:6,:7,:8,:9)""",
    'delete_main_dtm_table': """DELETE FROM user_dwhpr.DTM_MISE_AFITECH_COMMISSION
WHERE idtemps IN (SELECT idtemps FROM user_dwhpr.dim_temps WHERE jour BETWEEN :first_day_of_month AND :date_fin )""", # Utilise firstDay et fin
    'insert_main_dtm_table': """INSERT INTO user_dwhpr.DTM_MISE_AFITECH_COMMISSION(
DEBUT_PERIODE ,FIN_PERIODE ,PARTNER ,PAYEMENT_PROVIDER ,TOTAL_COMMISSON ,DEPOSIT_TOTAL_AMOUNT
,DEPOSIT_COUNT ,WITHDRAWAL_TOTAL_AMOUNT ,WITHDRAWAL_COUNT ,IDTEMPS,MOIS, ANNEE )
(
    SELECT TO_CHAR(TO_DATE(TRIM(SUBSTR(DEBUT_PERIODE,1,10)),'YYYY/MM/DD'),'DD/MM/YYYY'),
        TO_CHAR(TO_DATE(TRIM(SUBSTR(FIN_PERIODE,1,10)),'YYYY/MM/DD'),'DD/MM/YYYY') AS JOUR,
            PARTNER,
            PAYEMENT_PROVIDER,
            NVL(TOTAL_COMMISSON,0),
            NVL(DEPOSIT_TOTAL_AMOUNT,0),
            NVL(DEPOSIT_COUNT,0),
            NVL(WITHDRAWAL_TOTAL_AMOUNT,0),
            NVL(WITHDRAWAL_COUNT,0),Te.idtemps AS IDTEMPS,Te.MOISC AS MOIS,Te.ANNEEC AS ANNEE
        FROM optiwaretemp.SRC_PRD_AFITECH_COMMISSION F, user_dwhpr.DIM_TEMPS Te
    WHERE TO_DATE(TRIM(SUBSTR(f.FIN_PERIODE,1,10)),'YYYY/MM/DD') = TO_DATE(TRIM(SUBSTR(Te.jour,1,10)),'DD/MM/RR')
)""",
    'cleanup_temp': """DELETE FROM optiwaretemp.SRC_PRD_AFITECH_COMMISSION"""
}

def get_queries():
    return QUERIES
