QUERIES = {
    # Initial Truncate for temp table
    'truncate_temp_minishop': """TRUNCATE TABLE OPTIWARETEMP.SRC_PRD_MINI_SHOP""",

    # Insert into temp table from CSV data
    'insert_temp_minishop': """INSERT INTO OPTIWARETEMP.SRC_PRD_MINI_SHOP( "DATE"
      ,"ETABLISSEMENT" ,"JEU" ,"TERMINAL" ,"VENDEUR" ,"MONTANT A VERSER" ,"MONTANT A PAYER")
      VALUES(:1, :2, :3, :4, :5, :6, :7)""",

    # Deletes from main tables
    'delete_main_fait_vente': """DELETE FROM user_dwhpr.fait_vente
WHERE IDJEUX IN (469,470)
AND idtemps IN (SELECT idtemps FROM user_dwhpr.dim_temps WHERE jour BETWEEN :date_debut AND :date_fin )""",
    'delete_main_fait_lots': """DELETE FROM user_dwhpr.fait_lots
WHERE IDJEUX IN (469,470)
AND idtemps IN (SELECT idtemps FROM user_dwhpr.dim_temps WHERE jour BETWEEN :date_debut AND :date_fin )""",

    # Inserts into DIM_TERMINAL
    'insert_dim_terminal_existing_systems': """INSERT INTO USER_DWHPR.DIM_TERMINAL(IDCCS,OPERATEUR,STATUT,IDSYSTEME)
    SELECT IDCCS, OPERATEUR, '' STATUT, 174 IDSYSTEME
    FROM (   SELECT DISTINCT F.OPERATEUR, IDCCS,174 IDSYSTEME
       FROM(
               SELECT DISTINCT t.TERMINAL OPERATEUR, IDCCS
               FROM OPTIWARETEMP.SRC_PRD_MINI_SHOP t ,USER_DWHPR.DIM_TERMINAL L
               WHERE t.TERMINAL= L.OPERATEUR
               AND IDSYSTEME IN(166,2)
          )F
          WHERE F.OPERATEUR NOT IN (SELECT OPERATEUR FROM USER_DWHPR.DIM_TERMINAL WHERE IDSYSTEME = 174)
     ) S""",
    'insert_dim_terminal_solidicon': """INSERT INTO USER_DWHPR.DIM_TERMINAL(IDCCS,OPERATEUR,STATUT,IDSYSTEME)
SELECT  388 IDCCS, OPERATEUR, '' STATUT, 174 IDSYSTEME
    FROM (
               SELECT DISTINCT TERMINAL OPERATEUR
                FROM OPTIWARETEMP.SRC_PRD_MINI_SHOP
               WHERE TERMINAL NOT IN (SELECT OPERATEUR FROM USER_DWHPR.DIM_TERMINAL WHERE IDSYSTEME=174)
			   AND JEU = 'SOLIDICON'
         ) S
GROUP BY OPERATEUR""",

    # Inserts into main FAIT tables
    'insert_main_fait_vente': """INSERT INTO USER_DWHPR.FAIT_VENTE(IDVENDEUR,IDTERMINAL,IDTEMPS,IDJEUX,MONTANT,MONTANT_ANNULE,TICKET_EMIS,TICKET_ANNULE,ANNEE,MOIS,JOUR)
SELECT  7181 IDVENDEUR,
        T.IDTERMINAL,
		Te.IDTEMPS,
		F.IDJEUX,
		MONTANT,
		0 MONTANT_ANNULE,
       '' TICKET_EMIS,
		'' TICKET_ANNULE,
TO_CHAR(Te.JOUR,'YYYY') ANNEE,
TO_CHAR(Te.JOUR,'MM') MOIS,
REPLACE(TO_CHAR(Te.JOUR,'DD/MM/YYYY'),'/','') JOUR
    FROM (
               SELECT TO_DATE(SUBSTR("DATE",1,10),'yyyy-mm-dd') DATEOP,
			    TERMINAL OPERATEUR,
              TO_NUMBER(TRIM(REPLACE(REPLACE("MONTANT A VERSER",'.',','),' ',''))) MONTANT,
             CASE WHEN UPPER(TRIM(JEU)) LIKE 'SOLIDICON' THEN 470 ELSE 469 END IDJEUX
                FROM OPTIWARETEMP.SRC_PRD_MINI_SHOP
				WHERE NOT (JEU = 'ALR HONORE GAMING' AND TERMINAL = '10961')
         ) F, USER_DWHPR.DIM_TERMINAL T, USER_DWHPR.DIM_TEMPS Te
WHERE UPPER(TRIM(T.OPERATEUR)) = UPPER(TRIM(F.OPERATEUR ))
AND T.IDSYSTEME=174
AND Te.JOUR = F.DATEOP""",
    'insert_main_fait_lots': """INSERT INTO USER_DWHPR.FAIT_LOTS(IDVENDEUR,IDTERMINAL,IDTEMPS,IDJEUX,MONTANT,MONTANT_ANNULE,PAIEMENTS,ANNEE,MOIS,JOUR)
SELECT  7181 IDVENDEUR, T.IDTERMINAL, Te.IDTEMPS,
   F.IDJEUX, MONTANT, 0 MONTANT_ANNULE,
        NVL(PAIEMENTS,0) PAIEMENTS,
		TO_CHAR(Te.JOUR,'YYYY') ANNEE,
      TO_CHAR(Te.JOUR,'MM') MOIS,
       REPLACE(TO_CHAR(Te.JOUR,'DD/MM/YYYY'),'/','') JOUR
    FROM (
             SELECT TO_DATE(SUBSTR("DATE",1,10),'yyyy-mm-dd') DATEOP,
			    TERMINAL OPERATEUR,
				 TO_NUMBER(TRIM(REPLACE(REPLACE("MONTANT A VERSER",'.',','),' ',''))) MONTANT,
                   TO_NUMBER(TRIM(REPLACE(REPLACE("MONTANT A PAYER",'.',','),' ',''))) PAIEMENTS,
                CASE WHEN UPPER(TRIM(JEU)) LIKE 'SOLIDICON' THEN 470 ELSE 469 END IDJEUX
                FROM OPTIWARETEMP.SRC_PRD_MINI_SHOP
				WHERE NOT (JEU = 'ALR HONORE GAMING' AND TERMINAL = '10961')
         ) F, USER_DWHPR.DIM_TERMINAL T, USER_DWHPR.DIM_TEMPS Te
WHERE  UPPER(TRIM(T.OPERATEUR)) = UPPER(TRIM(F.OPERATEUR ))
  AND T.IDSYSTEME=174
  AND Te.JOUR= F.DATEOP""",

    # Merge into DTM_MINI_SHOP
    'merge_dtm_mini_shop': """MERGE INTO USER_DWHPR.DTM_MINI_SHOP R0 USING (
      SELECT  Te.IDTEMPS, Te.ANNEEC ANNEE, Te.MOISC MOIS,
                TO_DATE(SUBSTR("DATE",1,10),'yyyy-mm-dd') DATEOP,
                  TERMINAL OPERATEUR, JEU AS PRODUIT,
             SUM(TO_NUMBER(TRIM(REPLACE(REPLACE("MONTANT A VERSER",'.',','),' ','')))) MONTANT,
              SUM( TO_NUMBER(TRIM(REPLACE(REPLACE("MONTANT A PAYER",'.',','),' ','')))) PAIEMENTS
            FROM OPTIWARETEMP.SRC_PRD_MINI_SHOP , USER_DWHPR.DIM_TEMPS Te
            WHERE te.JOUR = TO_DATE(SUBSTR("DATE",1,10),'yyyy-mm-dd')
            AND  NOT (JEU = 'ALR HONORE GAMING' AND TERMINAL = '10961')
           GROUP BY Te.IDTEMPS,Te.ANNEEC, Te.MOISC,TO_DATE(SUBSTR("DATE",1,10),'yyyy-mm-dd'),TERMINAL,JEU
    ) R1
    ON (R0.IDTEMPS=R1.IDTEMPS AND R0.ANNEE= R1.ANNEE AND R0.MOIS=R1.MOIS AND R0.JOUR=R1.DATEOP AND R0.OPERATEUR=R1.OPERATEUR  AND R0.PRODUIT=R1.PRODUIT)
    WHEN MATCHED THEN UPDATE SET R0.CA=R1.MONTANT, R0.LOTS=R1.PAIEMENTS
    WHEN NOT MATCHED THEN INSERT (IDTEMPS, ANNEE, MOIS, JOUR,CA,LOTS,PRODUIT,OPERATEUR)
                  VALUES (R1.IDTEMPS, R1.ANNEE, R1.MOIS, R1.DATEOP, R1.MONTANT, R1.PAIEMENTS,R1.PRODUIT,R1.OPERATEUR)""",

    # Merges into DTM_CA_DAILY
    'merge_dtm_ca_daily_minishop': """MERGE INTO DTM_CA_DAILY R0 USING
(
SELECT Te.ANNEEC,Te.MOISC,Te.JOUR, SUM(COALESCE(F.MONTANT,0)) - SUM(COALESCE(F.MONTANT_ANNULE,0)) AS CA_MINI_SHOP
FROM FAIT_VENTE F, DIM_JEUX J , DIM_TEMPS Te
WHERE F.IDJEUX=J.IDJEUX
  AND F.IDTEMPS=Te.IDTEMPS
  AND F.IDJEUX=469
  AND Te.JOUR BETWEEN :date_debut AND :date_fin
GROUP BY Te.ANNEEC,Te.MOISC,Te.JOUR
) R1
ON ( R0.ANNEE = R1.ANNEEC AND R0.MOIS=R1.MOISC AND R0.JOUR=R1.JOUR)
WHEN MATCHED THEN UPDATE SET R0.CA_MINI_SHOP=R1.CA_MINI_SHOP""",
    'merge_dtm_ca_daily_virtuelshop': """MERGE INTO DTM_CA_DAILY R0 USING
(
SELECT Te.ANNEEC,Te.MOISC,Te.JOUR, SUM(COALESCE(F.MONTANT,0)) - SUM(COALESCE(F.MONTANT_ANNULE,0)) AS CA_VIRTUEL_SHOP
FROM FAIT_VENTE F, DIM_JEUX J , DIM_TEMPS Te
WHERE F.IDJEUX=J.IDJEUX
  AND F.IDTEMPS=Te.IDTEMPS
  AND F.IDJEUX=470
  AND Te.JOUR BETWEEN :date_debut AND :date_fin
GROUP BY Te.ANNEEC,Te.MOISC,Te.JOUR
) R1
ON ( R0.ANNEE = R1.ANNEEC AND R0.MOIS=R1.MOISC AND R0.JOUR=R1.JOUR)
WHEN MATCHED THEN UPDATE SET R0.CA_VIRTUEL_SHOP=R1.CA_VIRTUEL_SHOP""",

    # Merges into DTM_CA
    'merge_dtm_ca_minishop': """MERGE INTO user_dwhpr.dtm_ca t
USING (
    SELECT F.ANNEE ANNEE, F.MOIS MOIS, SUM(COALESCE(MONTANT,0))-SUM(COALESCE(MONTANT_ANNULE,0)) CA_MINI_SHOP
    FROM USER_DWHPR.FAIT_VENTE F, USER_DWHPR.DIM_TERMINAL Ter,USER_DWHPR.DIM_TEMPS Te, USER_DWHPR.DIM_JEUX J
    WHERE Te.IDTEMPS=F.IDTEMPS
        AND Te.ANNEEC IN (:year_debut, :year_fin)
        AND F.IDJEUX=J.IDJEUX AND F.IDJEUX = 469
        AND F.idterminal=Ter.idterminal AND Ter.idsysteme = 174
    GROUP BY F.ANNEE , F.MOIS
) g
ON (t.annee = g.annee AND t.mois=g.mois)
WHEN MATCHED THEN UPDATE SET t.CA_MINI_SHOP= g.CA_MINI_SHOP""",
    'merge_dtm_ca_virtuelshop': """MERGE INTO user_dwhpr.dtm_ca t
USING (
    SELECT F.ANNEE ANNEE, F.MOIS MOIS, SUM(COALESCE(MONTANT,0))-SUM(COALESCE(MONTANT_ANNULE,0)) CA_VIRTUEL_SHOP
    FROM USER_DWHPR.FAIT_VENTE F, USER_DWHPR.DIM_TERMINAL Ter,USER_DWHPR.DIM_TEMPS Te, USER_DWHPR.DIM_JEUX J
    WHERE Te.IDTEMPS=F.IDTEMPS
        AND Te.ANNEEC IN (:year_debut, :year_fin)
        AND F.IDJEUX=J.IDJEUX AND F.IDJEUX = 470
        AND F.idterminal=Ter.idterminal AND Ter.idsysteme = 174
    GROUP BY F.ANNEE , F.MOIS
) g
ON (t.annee = g.annee AND t.mois=g.mois)
WHEN MATCHED THEN UPDATE SET t.CA_VIRTUEL_SHOP= g.CA_VIRTUEL_SHOP""",

    # Archive and cleanup temp table
    'delete_archive_minishop': """DELETE FROM OPTIWARETEMP.AR_MINI_SHOP
    WHERE "DATE" IN (SELECT DISTINCT "DATE" FROM OPTIWARETEMP.SRC_PRD_MINI_SHOP)""", # Assuming "DATE" column exists and is comparable
    'insert_archive_minishop': """INSERT INTO OPTIWARETEMP.AR_MINI_SHOP
    SELECT * FROM OPTIWARETEMP.SRC_PRD_MINI_SHOP"""
    # Final truncate is 'truncate_temp_minishop'
}

def get_queries():
    return QUERIES
